import { describe, expect, it } from 'vitest';
import { GenerateBrewfileUseCase } from './generate-brewfile.use-case';
import { Package } from '@/types';

const createPackage = (id: string, cask = false): Package => ({
  id,
  name: id,
  description: 'Test package',
  category: 'tools',
  platforms: { macos: true, linux: false },
  defaultVersion: 'stable',
  versions: [
    { 
      id: 'stable', 
      label: 'Stable', 
      macCommand: cask ? `brew install --cask ${id}` : `brew install ${id}`, 
      linuxCommand: `sudo apt install ${id}` 
    },
  ],
});

describe('GenerateBrewfileUseCase', () => {
  const useCase = new GenerateBrewfileUseCase();

  it('should return Brewfile header for empty packages', () => {
    const result = useCase.execute([]);

    // Even with no packages, it generates the header
    expect(result).toContain('# Brewfile generated by SudoStart');
    expect(result).toContain('# Date:');
  });

  it('should generate Brewfile for packages', () => {
    const packages = [
      createPackage('git'),
      createPackage('nodejs'),
    ];

    const result = useCase.execute(packages);

    expect(result).toContain('brew "git"');
    expect(result).toContain('brew "nodejs"');
  });

  it('should detect cask packages', () => {
    const packages = [
      createPackage('vscode', true),
    ];

    const result = useCase.execute(packages);

    expect(result).toContain('cask "vscode"');
  });

  it('should format as valid Brewfile', () => {
    const packages = [
      createPackage('git'),
      createPackage('docker'),
    ];

    const result = useCase.execute(packages);

    expect(result).toContain('# Brewfile');
    expect(result).toContain('generated');
  });
});
