'use client';

import { useState } from 'react';

const brandColors: Record<string, string> = {
  '1password': '181717',
  alacritty: 'F46D01',
  angular: 'DD0031',
  ansible: 'EE0000',
  apache: 'D22128',
  arc: '5257FA',
  audacity: '0000CC',
  amazonaws: 'FF9900',
  antigravity: '4285F4',
  microsoftazure: '0078D4',
  bat: '31369E',
  bitwarden: '175DDC',
  blender: 'F5792A',
  brave: 'FB542B',
  bun: '000000',
  cassandra: '1287B1',
  clickhouse: 'FFCC00',
  clojure: '5881D8',
  cmake: '064F8C',
  cockroachlabs: '6933FF',
  cpp: '00599C',
  curl: '073551',
  cursor: '000000',
  deno: '000000',
  discord: '5865F2',
  django: '092E20',
  docker: '2496ED',
  electron: '47848F',
  elixir: '4B275F',
  emacs: '5D2E7A',
  erlang: 'A90533',
  express: '000000',
  ffmpeg: '007808',
  figma: 'F24E1E',
  firefox: 'FF7139',
  flask: '000000',
  flutter: '02569B',
  go: '00ADD8',
  godotengine: '478CBF',
  gnupg: '0093DD',
  gradle: '02303A',
  googlechrome: '4285F4',
  haskell: '5D4F85',
  httpie: 'FF4040',
  hyper: '000000',
  imagemagick: 'C248B5',
  inkscape: '000000',
  insomnia: '4000BF',
  intellijidea: '000000',
  ionic: '3880FF',
  iterm2: '14B866',
  oracle: 'F80000',
  jenkins: 'D24939',
  jupyter: 'F37626',
  kitty: '000000',
  kotlin: '7F52FF',
  krita: '23A9F2',
  kubernetes: '326CE5',
  logseq: '8BB94A',
  lua: '2C2D72',
  mariadb: '003545',
  apachemaven: 'C71A36',
  microsoftedge: '0078D7',
  microsoftteams: '6264A7',
  mongodb: '47A248',
  canonical: 'E95420',
  mysql: '4479A1',
  neo4j: '008CC1',
  neovim: '57A143',
  netlify: '00C7B7',
  nextdotjs: '000000',
  ngrok: '1F1E37',
  nginx: '009639',
  nodedotjs: '339933',
  notion: '000000',
  npm: 'CB3837',
  numpy: '013243',
  obsstudio: '302E31',
  obsidian: '7C3AED',
  zsh: 'F15A24',
  openssh: '000000',
  openssl: '7DA40A',
  packer: '02A8EF',
  pandas: '150458',
  pandoc: '333333',
  perl: '39457E',
  php: '777BB4',
  pnpm: 'F69220',
  podman: '892CA3',
  postman: 'FF6C37',
  postgresql: '4169E1',
  prometheus: 'E6522C',
  pulumi: '8A3391',
  python: '3776AB',
  qt: '41CD52',
  r: '276DC3',
  raycast: 'FF6363',
  react: '61DAFB',
  rectangle: '000000',
  redis: 'DC382D',
  ruby: 'CC342D',
  rust: '000000',
  scala: 'DC322F',
  slack: '4A154B',
  sqlite: '003B57',
  stripe: '635BFF',
  sublimetext: 'FF9800',
  supabase: '3ECF8E',
  tauri: 'FFC131',
  telegram: '26A5E4',
  terraform: '844FBA',
  tensorflow: 'FF6F00',
  tmux: '1BB91F',
  todoist: 'E44332',
  unity: '000000',
  unrealengine: '0E1128',
  vagrant: '1868F2',
  vercel: '000000',
  vim: '019733',
  vivaldi: 'EF3939',
  visualstudiocode: '007ACC',
  vuedotjs: '4FC08D',
  warp: '01A4FF',
  gnu: 'A42E2B',
  wireguard: '88171A',
  windsurf: '000000',
  xcode: '147EFB',
  yarn: '2C8EBB',
  zedindustries: '000000',
  zoom: '2D8CFF',
  calendar: '0078D4',
  linux: 'FCC624',
  apple: '000000',
  containers: '892CA3',
  rss: 'FFA500',
  gnometerminal: '2E3436',
};

const iconSlug: Record<string, string> = {
  '1password': '1password',
  '1password-cli': '1password',
  alacritty: 'alacritty',
  angular: 'angular',
  ansible: 'ansible',
  apache: 'apache',
  arc: 'arc',
  audacity: 'audacity',
  'aws-cli': 'amazonaws',
  'aws-cdk': 'amazonaws',
  antigravity: 'google',
  'azure-cli': 'microsoftazure',
  bat: 'bat',
  bitwarden: 'bitwarden',
  'bitwarden-cli': 'bitwarden',
  blender: 'blender',
  bottom: 'gnometerminal',
  brave: 'brave',
  bun: 'bun',
  calcurse: 'calendar',
  cassandra: 'apache',
  clickhouse: 'clickhouse',
  clojure: 'clojure',
  cmake: 'cmake',
  cockroachdb: 'cockroachlabs',
  cordova: 'apache',
  cpp: 'cplusplus',
  curl: 'curl',
  cursor: 'cursor',
  delta: 'git',
  deno: 'deno',
  discord: 'discord',
  django: 'django',
  docker: 'docker',
  'docker-compose': 'docker',
  'docker-desktop': 'docker',
  dust: 'linux',
  electron: 'electron',
  elixir: 'elixir',
  emacs: 'emacs',
  erlang: 'erlang',
  exa: 'linux',
  express: 'express',
  fail2ban: 'linux',
  fd: 'linux',
  ffmpeg: 'ffmpeg',
  figma: 'figma',
  firefox: 'firefox',
  flask: 'flask',
  flutter: 'flutter',
  fork: 'git',
  fzf: 'linux',
  gcloud: 'googlecloud',
  ghostty: 'gnometerminal',
  gimp: 'gimp',
  git: 'git',
  'git-lfs': 'git',
  'github-cli': 'github',
  'github-desktop': 'github',
  glances: 'linux',
  go: 'go',
  godot: 'godotengine',
  gpg: 'gnupg',
  gradle: 'gradle',
  'google-chrome': 'googlechrome',
  haskell: 'haskell',
  helm: 'kubernetes',
  htop: 'linux',
  httpie: 'httpie',
  hyper: 'hyper',
  imagemagick: 'imagemagick',
  inkscape: 'inkscape',
  insomnia: 'insomnia',
  intellij: 'intellijidea',
  ionic: 'ionic',
  iterm2: 'iterm2',
  java: 'oracle',
  jenkins: 'jenkins',
  jq: 'linux',
  jupyter: 'jupyter',
  kitty: 'kitty',
  kotlin: 'kotlin',
  krita: 'krita',
  kubectl: 'kubernetes',
  kustomize: 'kubernetes',
  lazygit: 'git',
  lima: 'linux',
  logseq: 'logseq',
  lua: 'lua',
  make: 'cmake',
  mariadb: 'mariadb',
  maven: 'apachemaven',
  matplotlib: 'python',
  'microsoft-edge': 'microsoftedge',
  'microsoft-teams': 'microsoftteams',
  minikube: 'kubernetes',
  mongodb: 'mongodb',
  multipass: 'canonical',
  mysql: 'mysql',
  neo4j: 'neo4j',
  neovim: 'neovim',
  'netlify-cli': 'netlify',
  newsboat: 'rss',
  nextjs: 'nextdotjs',
  ngrok: 'ngrok',
  nginx: 'nginx',
  nodejs: 'nodedotjs',
  notion: 'notion',
  npm: 'npm',
  numpy: 'numpy',
  nvm: 'nodedotjs',
  'obs-studio': 'obsstudio',
  obsidian: 'obsidian',
  'oh-my-zsh': 'zsh',
  openssh: 'openssh',
  openssl: 'openssl',
  packer: 'packer',
  pandas: 'pandas',
  pandoc: 'pandoc',
  perl: 'perl',
  php: 'php',
  pnpm: 'pnpm',
  podman: 'podman',
  postman: 'postman',
  postgresql: 'postgresql',
  prometheus: 'prometheus',
  pulumi: 'pulumi',
  pyenv: 'python',
  python3: 'python',
  qt: 'qt',
  r: 'r',
  raycast: 'raycast',
  react: 'react',
  'react-native': 'react',
  rbenv: 'ruby',
  rectangle: 'apple',
  redis: 'redis',
  ripgrep: 'linux',
  ruby: 'ruby',
  rust: 'rust',
  scala: 'scala',
  sdkman: 'java',
  skopeo: 'containers',
  slack: 'slack',
  sqlite3: 'sqlite',
  'stripe-cli': 'stripe',
  'sublime-merge': 'sublimetext',
  'supabase-cli': 'supabase',
  taskwarrior: 'linux',
  tauri: 'tauri',
  telegram: 'telegram',
  terraform: 'terraform',
  tensorflow: 'tensorflow',
  timescaledb: 'postgresql',
  timewarrior: 'linux',
  tmux: 'tmux',
  todoist: 'todoist',
  tower: 'git',
  unity: 'unity',
  'unreal-engine': 'unrealengine',
  vagrant: 'vagrant',
  'vercel-cli': 'vercel',
  vim: 'vim',
  vivaldi: 'vivaldi',
  vscode: 'visualstudiocode',
  vue: 'vuedotjs',
  warp: 'warp',
  wget: 'gnu',
  wireguard: 'wireguard',
  windsurf: 'windsurf',
  xcode: 'xcode',
  yarn: 'yarn',
  zed: 'zedindustries',
  'zen-browser': 'firefox',
  zoom: 'zoom',
  zsh: 'zsh',
};

export function AppIcon({ id, name, size = 40, className = '' }: {
  id: string;
  name: string;
  size?: number;
  className?: string;
}) {
  const [error, setError] = useState(false);
  const slug = iconSlug[id];
  const color = brandColors[id] || brandColors[slug] || '888888';
  const iconUrl = slug ? `https://cdn.simpleicons.org/${slug}/${color}` : null;

  if (!iconUrl || error) {
    return (
      <span
        className={`flex items-center justify-center rounded-xl app-icon-tile font-bold shrink-0 ${className}`}
        style={{ width: size, height: size, fontSize: size * 0.4 }}
      >
        {name.charAt(0).toUpperCase()}
      </span>
    );
  }

  return (
    <span
      className={`flex items-center justify-center shrink-0 ${className}`}
      style={{ width: size, height: size }}
    >
      <img
        src={iconUrl}
        alt=""
        width={Math.round(size * 0.7)}
        height={Math.round(size * 0.7)}
        onError={() => setError(true)}
        className="object-contain"
        draggable={false}
      />
    </span>
  );
}
