import { Package } from '@/types';

export const databaseApps: Package[] = [
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    description: '💾 Advanced open-source relational database',
    category: 'database',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    linuxCommandTemplate: 'curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /usr/share/keyrings/pgdg.gpg && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/pgdg.gpg] http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list && sudo apt-get update && sudo apt-get install -y postgresql-${VERSION_MAJOR} postgresql-contrib',
    macosCommandTemplate: 'brew install postgresql@${VERSION_MAJOR}',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install postgresql',
        linuxCommand: 'sudo apt-get install -y postgresql postgresql-contrib',
      },
    ],
  },
  {
    id: 'mysql',
    name: 'MySQL',
    description: '🐬 The world\'s most popular open-source relational database',
    category: 'database',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    linuxCommandTemplate: 'wget https://dev.mysql.com/get/mysql-apt-config_0.8.29-1_all.deb -O /tmp/mysql-apt-config.deb && sudo dpkg -i /tmp/mysql-apt-config.deb && sudo apt-get update && sudo apt-get install -y mysql-server-${VERSION_MAJOR}',
    macosCommandTemplate: 'brew install mysql@${VERSION_MAJOR}',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install mysql && brew services start mysql',
        linuxCommand: 'sudo apt-get install -y mysql-server && sudo systemctl start mysql && sudo systemctl enable mysql',
      },
    ],
  },
  {
    id: 'mariadb',
    name: 'MariaDB',
    description: '🦭 Community-developed MySQL fork — drop-in replacement',
    category: 'database',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    linuxCommandTemplate: 'sudo apt-get install -y mariadb-server-${VERSION_MAJOR}',
    macosCommandTemplate: 'brew install mariadb@${VERSION_MAJOR}',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install mariadb && brew services start mariadb',
        linuxCommand: 'sudo apt-get install -y mariadb-server && sudo systemctl start mariadb && sudo systemctl enable mariadb',
      },
    ],
  },
  {
    id: 'sqlite3',
    name: 'SQLite',
    description: '🗃️ Lightweight, serverless, self-contained SQL database engine',
    category: 'database',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install sqlite',
        linuxCommand: 'sudo apt-get install -y sqlite3',
      },
    ],
  },
  {
    id: 'redis',
    name: 'Redis',
    description: '🧠 In-memory data structure store',
    category: 'database',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    linuxCommandTemplate: 'wget https://download.redis.io/releases/redis-${VERSION_NO_V}.tar.gz && tar xzf redis-${VERSION_NO_V}.tar.gz && cd redis-${VERSION_NO_V} && make && sudo make install',
    macosCommandTemplate: 'brew install redis@${VERSION_MAJOR}',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install redis',
        linuxCommand: 'sudo apt-get install -y redis-server',
      },
    ],
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    description: '🍃 NoSQL document database',
    category: 'database',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    linuxCommandTemplate: 'curl -fsSL https://www.mongodb.org/static/pgp/server-${VERSION_MAJOR}.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-server-${VERSION_MAJOR}.0.gpg && echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-${VERSION_MAJOR}.0.gpg ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/${VERSION_MAJOR}.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-${VERSION_MAJOR}.0.list && sudo apt-get update && sudo apt-get install -y mongodb-org=${VERSION_NO_V}',
    macosCommandTemplate: 'brew tap mongodb/brew && brew install mongodb-community@${VERSION_MAJOR}',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install mongodb-community',
        linuxCommand: 'sudo apt-get install -y gnupg curl && curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-server-7.0.gpg && echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") /mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list && sudo apt-get update && sudo apt-get install -y mongodb-org',
      },
    ],
  },
  {
    id: 'cockroachdb',
    name: 'CockroachDB',
    description: '🪳 Distributed SQL database with horizontal scalability',
    category: 'database',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install cockroachdb/tap/cockroach',
        linuxCommand: 'curl https://binaries.cockroachdb.com/cockroach-v23.1.11.linux-amd64.tgz | tar -xz && sudo cp -i cockroach-v23.1.11.linux-amd64/cockroach /usr/local/bin/',
      },
    ],
  },
  {
    id: 'cassandra',
    name: 'Cassandra',
    description: '🔱 NoSQL distributed database for big data',
    category: 'database',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install cassandra',
        linuxCommand: 'sudo apt-get install -y cassandra',
      },
    ],
  },
  {
    id: 'neo4j',
    name: 'Neo4j',
    description: '🕸️ Graph database for connected data',
    category: 'database',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install neo4j',
        linuxCommand: 'wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add - && echo "deb https://debian.neo4j.com stable latest" | sudo tee /etc/apt/sources.list.d/neo4j.list && sudo apt-get update && sudo apt-get install -y neo4j',
      },
    ],
  },
  {
    id: 'clickhouse',
    name: 'ClickHouse',
    description: '⚡ Fast columnar DBMS for OLAP',
    category: 'database',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install clickhouse',
        linuxCommand: 'sudo apt-get install -y apt-transport-https ca-certificates dirmngr && sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4 && echo "deb https://repo.clickhouse.com/deb/stable/ main/" | sudo tee /etc/apt/sources.list.d/clickhouse.list && sudo apt-get update && sudo apt-get install -y clickhouse-server clickhouse-client',
      },
    ],
  },
  {
    id: 'timescaledb',
    name: 'TimescaleDB',
    description: '⏱️ Time-series SQL database built on PostgreSQL',
    category: 'database',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install timescaledb',
        linuxCommand: 'sudo apt-get install -y timescaledb-postgresql-14',
      },
    ],
  },
];