import { Package } from '@/types';

export const utilityApps: Package[] = [
  {
    id: 'jq',
    name: 'jq',
    description: '🔍 Lightweight and flexible command-line JSON processor',
    category: 'utility',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    linuxCommandTemplate: 'wget https://github.com/jqlang/jq/releases/download/${VERSION}/jq-linux-amd64 -O /tmp/jq && sudo install -D -m755 /tmp/jq /usr/local/bin/jq',
    macosCommandTemplate: 'brew install jq',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install jq',
        linuxCommand: 'sudo apt-get install -y jq',
      },
    ],
  },
  {
    id: 'wget',
    name: 'wget',
    description: '⬇️ Network downloader supporting HTTP, HTTPS and FTP',
    category: 'utility',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install wget',
        linuxCommand: 'sudo apt-get install -y wget',
      },
    ],
  },
  {
    id: 'htop',
    name: 'htop',
    description: '📊 Interactive process viewer — a better top',
    category: 'utility',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    linuxCommandTemplate: 'wget https://github.com/htop-dev/htop/releases/download/${VERSION}/htop-${VERSION_NO_V}.tar.gz && tar -xzf htop-${VERSION_NO_V}.tar.gz && cd htop-${VERSION_NO_V} && ./configure && make && sudo make install && cd .. && rm -rf htop-${VERSION_NO_V}*',
    macosCommandTemplate: 'brew install htop',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install htop',
        linuxCommand: 'sudo apt-get install -y htop',
      },
    ],
  },
  {
    id: 'tmux',
    name: 'tmux',
    description: '🖥️ Terminal multiplexer — split panes, persist sessions over SSH',
    category: 'utility',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    linuxCommandTemplate: 'wget https://github.com/tmux/tmux/releases/download/${VERSION}/tmux-${VERSION_NO_V}.tar.gz && tar -xzf tmux-${VERSION_NO_V}.tar.gz && cd tmux-${VERSION_NO_V} && ./configure && make && sudo make install && cd .. && rm -rf tmux-${VERSION_NO_V}*',
    macosCommandTemplate: 'brew install tmux',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install tmux',
        linuxCommand: 'sudo apt-get install -y tmux',
      },
    ],
  },
  {
    id: 'openssh',
    name: 'OpenSSH',
    description: '🔐 Secure Shell client and server for encrypted remote access',
    category: 'utility',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install openssh',
        linuxCommand: 'sudo apt-get install -y openssh-client openssh-server',
      },
    ],
  },
  {
    id: 'ngrok',
    name: 'ngrok',
    description: '🌐 Expose local servers to the internet — essential for webhook dev',
    category: 'utility',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install --cask ngrok',
        linuxCommand: 'curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt-get update && sudo apt-get install -y ngrok',
      },
    ],
  },
  {
    id: 'insomnia',
    name: 'Insomnia',
    description: '🌙 Open-source API client for REST, GraphQL and gRPC',
    category: 'utility',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install --cask insomnia',
        linuxCommand: 'echo "deb [trusted=yes arch=amd64] https://packages.konghq.com/public/insomnia/deb/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/insomnia.list && sudo apt-get update && sudo apt-get install -y insomnia',
      },
    ],
  },
  {
    id: 'ripgrep',
    name: 'Ripgrep',
    description: '⚡ Fast grep alternative that respects .gitignore',
    category: 'utility',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install ripgrep',
        linuxCommand: 'sudo apt-get install -y ripgrep',
      },
    ],
  },
  {
    id: 'fd',
    name: 'fd',
    description: '🔍 Fast and user-friendly alternative to find',
    category: 'utility',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install fd',
        linuxCommand: 'sudo apt-get install -y fd-find',
      },
    ],
  },
  {
    id: 'fzf',
    name: 'fzf',
    description: '🎯 Command-line fuzzy finder with preview support',
    category: 'utility',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install fzf',
        linuxCommand: 'sudo apt-get install -y fzf',
      },
    ],
  },
  {
    id: 'bat',
    name: 'Bat',
    description: '🦇 Cat clone with syntax highlighting and Git integration',
    category: 'utility',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install bat',
        linuxCommand: 'sudo apt-get install -y bat',
      },
    ],
  },
  {
    id: 'exa',
    name: 'Exa',
    description: '📁 Modern replacement for ls with icons and colors',
    category: 'utility',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install exa',
        linuxCommand: 'sudo apt-get install -y exa',
      },
    ],
  },
  {
    id: 'dust',
    name: 'Dust',
    description: '💨 More intuitive version of du for disk usage',
    category: 'utility',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install dust',
        linuxCommand: 'cargo install du-dust',
      },
    ],
  },
  {
    id: 'bottom',
    name: 'Bottom',
    description: '📈 System monitor with customizable widgets',
    category: 'utility',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install bottom',
        linuxCommand: 'sudo apt-get install -y bottom',
      },
    ],
  },
  {
    id: 'glances',
    name: 'Glances',
    description: '👁️ Cross-platform system monitoring tool',
    category: 'utility',
    platforms: { macos: true, linux: true },
    defaultVersion: 'stable',
    versions: [
      {
        id: 'stable',
        label: 'Stable',
        macCommand: 'brew install glances',
        linuxCommand: 'sudo apt-get install -y glances',
      },
    ],
  },
];